spring:
  application:
    name: learningCenter
    frontUrl: http://localhost:5173
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:postgresql://localhost:5432/learning_center
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
aws:
  s3:
    bucket: learning-center-uploads
    region: eu-north-1
    access-key: AKIA5SE3DSUARHE423RL
    secret-key: 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


jwt:
  access:
    token:
      secretKey: 4f6162315a6b324d6731336c56417a426e4d3538426a76386d4e7751525a334e
      expire:
        date: 900000
  refresh:
    token:
      secretKey: 62354b526d4c6d645161394a46587042594a574768344d5a71314e3658564232
      expire:
        date: 604800000

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
